apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-pgbouncer-sa
  namespace: prod-hades
  annotations:
    iam.gke.io/gcp-service-account: prod-pgbouncer-gsa@your-gcp-project-id.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: prod-hades
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: prod-pgbouncer-sa
      projectID: your-gcp-project-id


---
# 1. Kubernetes Secret untuk SSL CA Cert
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-certs
  namespace: prod-hades
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: pgbouncer-certs
    creationPolicy: Owner
  data:
    - secretKey: server-ca.crt
      remoteRef:
        key: prod-pgbouncer-secrets
        property: server_ca
---
# 2. Kubernetes Secret untuk userlist.txt
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-secret
  namespace: prod-hades
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: pgbouncer-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        userlist.txt: |
          "prod_backend_hades_user" "{{ .db_password_user }}"
          "prod_backend_hades_transaction" "{{ .db_password_transaction }}"
        db_password_user: "{{ .db_password_user }}"
        db_password_transaction: "{{ .db_password_transaction }}"

  data:
    - secretKey: db_password_user
      remoteRef:
        key: prod-pgbouncer-secrets
        property: db_password_user
    - secretKey: db_password_transaction
      remoteRef:
        key: prod-pgbouncer-secrets
        property: db_password_transaction

