apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-secret
  namespace: prod
type: Opaque
stringData:
  userlist.txt: |
    "prod-email" "Prod2423rfwfa131dsdrce"
    "prod-frontend" "Proda2421D23r4ff551"
    "prod-icarus" "Proda2421eJFiwf4ffwew"
    "prod-zeus" "Proda03421roiF43R3FW2"
    "postgres" "ProdAdminPasswordChangeMe"
